server:
  port: 8080
spring:
  application:
    name: client
  datasource:
    username: soumic
    password: my_awesome_password
    url: jdbc:postgresql://localhost:5432/client
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
# for now we don't need the eureka
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true